bloodcenters/urls.py
#!-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'hemocentros/$', 'bloodcenters.views.bloodcenters_list',
                           name='bloodcenters_list'),
                       url(r'hemocentros/estado/(?P<state>[\w\W]+)/$',
                           'bloodcenters.views.bloodcenters_by_state', name='bloodcenters_by_state'),
                       url(r'hemocentros/(?P<slug>[-_\w]+)/$',
                           'bloodcenters.views.bloodcenter_detail', name='bloodcenter_detail'),
                       )

home/urls.py
#!-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'home.views.index', name='home'),
)

bloodcenters/models.py
#!-*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.gis.db import models

from model_utils import Choices
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField


class BloodCenter(TimeStampedModel, models.Model):
    name = models.CharField(_(u'nome'), max_length=64)
    email = models.EmailField(
        _(u'e-mail'), max_length=128, null=True, blank=True)
    website = models.URLField(
        _(u'site'), max_length=128, null=True, blank=True)
    admins = models.ManyToManyField(
        settings.AUTH_USER_MODEL, verbose_name=_('administradores'), blank=True)
    slug = AutoSlugField(populate_from='name', max_length=64,
                         unique=True, always_update=True, db_index=True)

    class Meta:
        verbose_name = _(u'hemocentro')
        verbose_name_plural = _(u'hemocentros')


class Address(TimeStampedModel, models.Model):
    blood_center = models.ForeignKey(BloodCenter, verbose_name=_('hemocentro'))
    zip_code = models.CharField(_(u'cep'), max_length=8)
    street = models.CharField(_(u'logradouro'), max_length=64)
    number = models.CharField(_(u'número'), blank=True, max_length=8)
    neighborhood = models.CharField(_(u'bairro'), blank=True, max_length=64)
    city = models.CharField(_(u'cidade'), max_length=64)
    state = models.CharField(_(u'estado'), max_length=64)
    position = models.PointField(
        verbose_name=_(u'posição'), null=True, blank=False, spatial_index=True)

    objects = models.GeoManager()

    class Meta:
        verbose_name = _(u'endereço')
        verbose_name_plural = _(u'endereços')


class Phone(TimeStampedModel):
    blood_center = models.ForeignKey(BloodCenter, verbose_name=_('hemocentro'))
    number = models.CharField(_(u'número'), max_length=16)

    class Meta:
        verbose_name = _(u'telefone')
        verbose_name_plural = _(u'telefones')


class BloodStock(TimeStampedModel, models.Model):
    blood_center = models.ForeignKey(BloodCenter, verbose_name=_('hemocentro'))
    BLOOD_SUPPLY_CHOICES = Choices(
        (0, 'NoStock', _(u'Sem estoque')),
        (1, 'Low', _(u'Baixo')),
        (2, 'Medium', _(u'Médio')),
        (3, 'High', _(u'Alto')),
    )
    o_negative_stock_level = models.SmallIntegerField(
        _(u'O-'), choices=BLOOD_SUPPLY_CHOICES)
    o_positive_stock_level = models.SmallIntegerField(
        _(u'O+'), choices=BLOOD_SUPPLY_CHOICES)
    a_negative_stock_level = models.SmallIntegerField(
        _(u'A-'), choices=BLOOD_SUPPLY_CHOICES)
    a_positive_stock_level = models.SmallIntegerField(
        _(u'A+'), choices=BLOOD_SUPPLY_CHOICES)
    b_negative_stock_level = models.SmallIntegerField(
        _(u'B-'), choices=BLOOD_SUPPLY_CHOICES)
    b_positive_stock_level = models.SmallIntegerField(
        _(u'B+'), choices=BLOOD_SUPPLY_CHOICES)
    ab_negative_stock_level = models.SmallIntegerField(
        _(u'AB-'), choices=BLOOD_SUPPLY_CHOICES)
    ab_positive_stock_level = models.SmallIntegerField(
        _(u'AB+'), choices=BLOOD_SUPPLY_CHOICES)

    class Meta:
        get_latest_by = 'modified'
        verbose_name = _(u'estoque de sangue')
        verbose_name_plural = _(u'estoques de sangue')

bloodcenters/views.py
#!-*- coding: utf-8 -*-
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from .models import BloodCenter, Address


def bloodcenters_list(request):
    bloodcenters = BloodCenter.objects.all().order_by('name')
    states = Address.objects.values('state').distinct().order_by('state')
    return render_to_response('bloodcenters/bloodcenters_list.html', {
        'bloodcenters': bloodcenters,
        'states': states
    }, context_instance=RequestContext(request))


def bloodcenters_by_state(request, state):
    bloodcenters = BloodCenter.objects.filter(
        address__state=state).order_by('name')
    states = Address.objects.values('state').distinct().order_by('state')
    return render_to_response('bloodcenters/bloodcenters_list.html', {
        'bloodcenters': bloodcenters,
        'states': states
    }, context_instance=RequestContext(request))


def bloodcenter_detail(request, slug):
    bloodcenter = get_object_or_404(BloodCenter, slug=slug)
    return render_to_response('bloodcenters/bloodcenter_detail.html', {
        'bloodcenter': bloodcenter
    }, context_instance=RequestContext(request))

bloodcenters/templates/bloodcenters/bloodcenter_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% blocktrans with name=bloodcenter.name city=bloodcenter.address_set.first.city state=bloodcenter.address_set.first.state %}{{ name }} em {{city}} - {{state}}{% endblocktrans %}{% endblock %}
{% block description %}{% blocktrans with name=bloodcenter.name city=bloodcenter.address_set.first.city state=bloodcenter.address_set.first.state %}Veja o endereço e o telefone do {{ name }} em {{city}} - {{state}}{% endblocktrans %}{% endblock %}
{% block og_title %}{% blocktrans with name=bloodcenter.name city=bloodcenter.address_set.first.city state=bloodcenter.address_set.first.state %}{{ name }} em {{city}} - {{state}}{% endblocktrans %}{% endblock %}
{% block og_description %}{% blocktrans with name=bloodcenter.name city=bloodcenter.address_set.first.city state=bloodcenter.address_set.first.state %}Veja o endereço e o telefone do {{ name }} em {{city}} - {{state}}{% endblocktrans %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12" itemscope itemtype="http://schema.org/MedicalOrganization">

        <h1 class="page-header" itemprop="name">{{ bloodcenter.name }}</h1>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><i class="fa fa-fw fa-hospital-o"></i> {% trans 'Informações' %}</h2>
            </div>
            <div class="panel-body">

                {% with bloodcenter.address_set.all|first as address %}
                <div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
                    <p>{% blocktrans with street=address.street number=address.number neighborhood=address.neighborhood %}<b>Endereço:</b> <span itemprop="streetAddress">{{ street }} {{ number }} - {{ neighborhood }}</span>{% endblocktrans %}</p>
                    <p>{% blocktrans with city=address.city state=address.state %}<b>Cidade:</b> <span itemprop="addressLocality">{{ city }}</span> - <span itemprop="addressRegion">{{ state }}</span>{% endblocktrans %}</p>
                    <p>{% blocktrans with zip=address.zip_code %}<b>CEP:</b> <span itemprop="postalCode">{{zip}}</span>{% endblocktrans %}</p>
                </div>
                {% endwith %}

                {% if bloodcenter.email %}
                    <p>{% blocktrans with email=bloodcenter.email %}<b>E-mail:</b> <a href="mailto:{{ email }}" itemprop="email">{{ email }}</a>{% endblocktrans %}</p>
                {% endif %}

                {% if bloodcenter.website %}
                    <p>{% blocktrans with site=bloodcenter.website %}<b>Site:</b> <a href="{{ site }}" itemprop="url">{{ site }}</a>{% endblocktrans %}</p>
                {% endif %}

                {% if bloodcenter.phone_set.all %}
                <ul class="list-inline">
                    <li><b>Telefone(s): </b></li>
                    {% for phone in bloodcenter.phone_set.all %}
                    <li><i class="fa fa-phone text-muted"></i> <a href="tel:{{ phone.number }}"><span itemprop="telephone">{{ phone.number }}</span></a></li>
                    {% endfor %}
                </ul>
                {% endif %}

                {% if bloodcenter.bloodstock_set.all %}
                    <hr>
                    {% with bloodcenter.bloodstock_set.all|first as bloodstock %}
                    <p>{% blocktrans with last_update=bloodstock.created %}<b>Estoque:</b> (Última atualização: {{ last_update }}){% endblocktrans %}</p>
                    <ul class="list-inline">
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with o_negative=bloodstock.get_o_negative_stock_level_display %} O- ({{ o_negative }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with o_positive=bloodstock.get_o_positive_stock_level_display %} O+ ({{ o_positive }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with a_negative=bloodstock.get_a_negative_stock_level_display %} A- ({{ a_negative }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with a_positive=bloodstock.get_a_positive_stock_level_display %} A+ ({{ a_positive }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with b_negative=bloodstock.get_b_negative_stock_level_display %} B- ({{ b_negative }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with b_positive=bloodstock.get_b_positive_stock_level_display %} B+ ({{ b_positive }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with ab_negative=bloodstock.get_ab_negative_stock_level_display %} AB- ({{ ab_negative }}){% endblocktrans %}</a></li>
                        <li><i class="fa fa-tint text-muted"></i>{% blocktrans with ab_positive=bloodstock.get_ab_positive_stock_level_display %} AB+ ({{ ab_positive }}){% endblocktrans %}</a></li>
                    </ul>
                    {% endwith %}
                {% endif %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

bloodcenters/templates/bloodcenters/bloodcenters_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans 'Hemocentros' %}{% endblock %}
{% block description %}{% blocktrans %}Consulte a lista completa de hemocentros e unidades de coleta da sua cidade/estado.{% endblocktrans %}{% endblock %}
{% block keywords %}{% blocktrans %}hemocentros, hemonúcleos, ponto de coleta, sangue, doadores, hemocentro, tipo sanguíneo, hemoterapia, O+, O-, A-, A+, B-, B+, AB-, AB+{% endblocktrans %}{% endblock %}
{% block og_title %}{% blocktrans %}Hemocentros{% endblocktrans %}{% endblock %}
{% block og_description %}{% blocktrans %}Consulte a lista completa de hemocentros e unidades de coleta da sua cidade/estado.{% endblocktrans %}{% endblock %}

{% block content %}

<h1 class="page-header">{% trans 'Hemocentros' %}</h1>

{% include 'messages.html' %}

<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url 'bloodcenters_list' %}">{% trans 'Todos os estados' %}</a></li>
        {% for state in states %}
            <li><a href="{% url 'bloodcenters_by_state' state.state %}">{{ state.state }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-9">
        {% for bloodcenter in bloodcenters %}
            <div class="panel panel-default" itemscope itemtype="http://schema.org/MedicalOrganization">
                <div class="panel-heading">
                    <h2 class="panel-title"><i class="fa fa-fw fa-hospital-o"></i> <a href="{% url 'bloodcenter_detail' bloodcenter.slug %}" itemprop="url"><span itemprop="name">{{ bloodcenter.name }}</span></a></h2>
                </div>
                <div class="panel-body">
                    {% with bloodcenter.address_set.all|first as address %}
                    <div itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
                        <p>{% blocktrans with street=address.street number=address.number neighborhood=address.neighborhood %}<b>Endereço:</b> <span itemprop="streetAddress">{{ street }} {{ number }} - {{ neighborhood }}</span>{% endblocktrans %}</p>
                        <p>{% blocktrans with city=address.city state=address.state %}<b>Cidade:</b> <span itemprop="addressLocality">{{ city }}</span> - <span itemprop="addressRegion">{{ state }}</span>{% endblocktrans %}</p>
                        <p>{% blocktrans with zip=address.zip_code %}<b>CEP:</b> <span itemprop="postalCode">{{zip}}</span>{% endblocktrans %}</p>
                    </div>
                    {% endwith %}
                    {% if bloodcenter.phone_set.all %}
                        <ul class="list-inline">
                        <li><b>Telefone(s): </b></li>
                        {% for phone in bloodcenter.phone_set.all %}
                            <li><i class="fa fa-phone text-muted"></i> <a href="tel:{{ phone.number }}"><span itemprop="telephone">{{ phone.number }}</span></a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            {% empty %}
            <p class="text-center">Nenhum hemocentro foi cadastrado ainda.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}